### ISSUE TITLE
Zenodo-compatible save file option

### ISSUE THREAD

**Issue by emmetaobrien** [CONP-PCNO/conp-dats-editor#3]
There is an issue with uploading `DATS.json` files as part of datasets intended for CONP through the Zenodo GUI, which rejects any files with the extension` .json`.  This issue is known at Zenodo (https://github.com/zenodo/zenodo/issues/1453) but does not seem to be regarded as a bug.

In order to address this, the proposed solution is to add an option for our DATS editor GUI to save its output in a file called simply `DATS`, with no extension.  The CONP Zenodo crawler will then be modified to automatically rename that file to `DATS.json` on ingestion.  As this will only be necessary for users generating datasets to submit via Zenodo, I propose labelling this option something like "Zenodo-compatible".

**Comment by cmadjar** [comment]
In the end, Zenodo is now supporting the upload of json files so no need to do anything regarding this anymore.
