### ISSUE TITLE
DATS editor-related feedback

### ISSUE THREAD

**Issue by emmetaobrien** [CONP-PCNO/conp-dats-editor#32]
Issues arising from the last couple of weeks' working closely with an external data provider using datalad to add new datasets:

- [x]  indicating what the  `derivedFrom` field is for needs to be emphasised, as that is still very easy for a user to misread.
- [x]  need to specify that the species description fields under `isAbout` are now mandatory
- [x] DATS.json with an empty `description` field under `primaryPublication->date` are not valid, this field does not exist in the schema; it is unclear where this error originates and it may already have been fixed.

**Comment by cmadjar** [comment]
https://github.com/CONP-PCNO/conp-dats-editor/pull/28 fixed the issue with the empty `description` field under `primaryPublication->date`

**Comment by cmadjar** [comment]
https://github.com/CONP-PCNO/conp-portal/pull/485
