### ISSUE TITLE
Add more license types to licenses drop-down 

### ISSUE THREAD

**Issue by liamiepops** [CONP-PCNO/conp-dats-editor#4]
There are more license types that user will want to avail of those currently available.

Currently Available:

**Creative Commons:**
CC BY
CC BY-SA
CC BY-ND
CC BY-NC
CC BY-NC-SA
CC BY-NC-ND

Proposed additions:

**Creative Commons:**
CC0

**Comment by cmadjar** [comment]
I cannot think of any other license types. @emmetaobrien?

**Comment by emmetaobrien** [comment]
Could any of the license options at https://opendatacommons.org/ be relevant to our users?

**Comment by cmadjar** [comment]
I guess so. Good catch @emmetaobrien !

So maybe we should add those too:
- ODbL
- ODC-By
- PDDL

@glatard @samirdas @jbpoline thoughts?

**Comment by cmadjar** [comment]
@liamocn I merged your PR. Can you ensure this is reflected in the portal? Thanks!

**Comment by liamiepops** [comment]
@cmadjar I've opened a PR just now https://github.com/CONP-PCNO/conp-portal/pull/351
