### ISSUE TITLE
Update GUI field description text to something more user friendly

### ISSUE THREAD

**Issue by cmadjar** [CONP-PCNO/conp-dats-editor#8]
Currently, the description present in https://github.com/CONP-PCNO/schema/blob/master/dataset_schema.json is being displayed in the tooltip section of the DATS GUI.

Some might need to be modified to a more user friendly description with some examples when it makes sense to have examples.

Two options:
- update the description directly in the schema
- update the description directly the DATS GUI

Note: some fields, like the fields in the extraProperties section of the JSON file will need to be edited directly within the GUI.

**Comment by cmadjar** [comment]
Discussed at the CONP dev meeting of October 14th, the descriptions will be updated in the DATS GUI editor directly, not the schema.

**Comment by cmadjar** [comment]
Plan on how to proceed with that item:

1) create a google spreadsheet with a more detailed description of all the fields present in the DATS GUI (@PapillonMcGill) Once the spreadsheet ready @cmadjar and @emmetaobrien could review the descriptions easily.

2) create a JSON file that will contain the description of the fields that the GUI could read and display since it has been decided not to modify the dataset_schema.json of CONP on Wednesday (@PapillonMcGill)

3) read the JSON file and display its description content in the DATS GUI (@liamocn)

@liamocn does that seem like a reasonable approach to you? When ready to create the JSON file, maybe @PapillonMcGill and @liamocn can discuss how to organize the file?

Thanks!

**Comment by emmetaobrien** [comment]
@liamocn: Values for the spreadsheet at https://docs.google.com/spreadsheets/d/1AwUuKHMwiAMcwfU0_3SuhxF-Bo7k-c8qZkRGD5iB_RE/edit?ts=5f9c67aa#gid=0 should be taken or updated from https://github.com/CONP-PCNO/conp-documentation/blob/master/CONP_DATS_fields.md which is the most detailed and up-to-date documentation of our usage of and extensions to DATS.json.

**Comment by PapillonMcGill** [comment]
@liamocn @cmadjar @emmetaobrien 

I put a PR https://github.com/CONP-PCNO/conp-documentation/pull/53 with the proposed adjustment and updated that files at the same time with what is on the Portal. Please review. Thanks.
